version: 2

sources:
  - name: src
    database: postgres
    schema: public
    tables:
      - name: source_customers
      - name: source_orders
      - name: source_wheat_usa
      - name: source_wheat_msk
